image: eclipse-temurin:25-jdk

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GIT_SUBMODULE_PATHS: src/main/resources/bundles
  GIT_SUBMODULE_DEPTH: 1

cache:
  key: gradle
  paths:
    - .gradle/caches
    - .gradle/wrapper

buildJar:
  stage: build
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew jar
  artifacts:
    name: "$CI_PROJECT_NAME"
    paths:
      - build/libs/$CI_PROJECT_NAME.jar
